apps/products/urls.py
from django.urls import path
from .views import add_product, product_list, product_details

app_name = "products"

urlpatterns = [
    path('add/', add_product, name="add_product"),
    path('', product_list, name="product_list"),
    path('<id>/', product_details, name="product_details"),
]

core/urls.py
from xml.etree.ElementInclude import include
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf.urls.static import static
from django.conf import settings
from .views import login_page, logout_page
app_name = "core"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('login/', login_page),
    path('logout/', logout_page, name="logout"),
    path('products/', include('apps.products.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.utils.translation import gettext as _

from django.contrib.auth.models import AbstractUser, BaseUserManager

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""
    username = None
    email = models.EmailField(_('email address'), unique=True)
    email_validation = models.BooleanField(default=False)
    modified_at = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.email

apps/marketplace/models.py
from django.db import models

# Create your models here.

apps/products/models.py
from unicodedata import category
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    title = models.CharField(_("Title"), max_length=150)
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(_("Title"), max_length=250)
    price = models.FloatField(_("Price"))
    image = models.ImageField(_("Image"), upload_to="products", null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name=_("Category"), on_delete=models.SET_NULL, null=True, blank=True) # Or Cascade

    def image_preview(self):
        from django.utils.html import format_html

        if self.image:
            return format_html('<img src="{}" alt="{}" height="200" />'.format(self.image.url, self.title))
        return ""
    @property
    def old_price(self):
        return self.price + 100
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return f'[{self.title}:{self.price}]'

apps/products/forms.py
from django import forms
from .models import Product
class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        # fields = ('title','price')
        exclude= ('id',)

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
class LoginForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('email','password')

apps/accounts/views.py
from django.shortcuts import render

# Create your views here.

apps/products/views.py
from django.shortcuts import redirect, render
from .forms import ProductForm
from .models import Product
from django.contrib.auth.decorators import login_required
from core.decorators import allowed_users
def product_list(request):
    prds = Product.objects.all()
    context = {
        'products': prds
    }
    return render(request, 'products/list.html', context)

@allowed_users(allowed_roles=['Test'])
def product_details(request, id):
    prd = Product.objects.filter(id=id).first()
    context = {
        'product': prd
    }
    return render(request, 'products/details.html', context)
"""
d = {
    "title": 'titre',
    "object": {
        "attrs": [1,2,3,4,5,6],
        'other': {'hack': 'it'}
    }
}
d['object']['other']['hack']
d.get('object').get('other').get('hack')
"""

@login_required(login_url="/login")
def add_product(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(data=request.POST)
        if form.is_valid():
            print(request.POST)
            form.save()
            return redirect('products:product_list')
            """
            p = Product(
                title= request.POST.get('title'),
                price=request.POST['price']
            )
            """
        else:
            form = ProductForm(data=request.POST)
    context = {
        'form': form
    }
    return render(request, 'products/add.html', context)

core/views.py
from django.shortcuts import redirect, render

from apps.products.models import Product, Category
from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user
from core.forms import LoginForm
def home(request):
    cat = Category.objects.filter(title = 'Clothes').first()
    ctx = {
        "products": Product.objects.filter(category=cat)
    }
    return render(request, 'home.html', ctx)

@unauthenticated_user
def login_page(request):
    form = LoginForm()
    ctx = {
        "form": form
    }
    if request.method == "POST":
        user = authenticate(username=request.POST.get('username'), password= request.POST.get('password'))
        if user is not None:
            # redirect to homepage
            login(request, user)
            return redirect('/')
    return render(request, 'login.html', ctx)

def logout_page(request):
    logout(request)
    return redirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ECommerce - {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/materia/bootstrap.min.css" integrity="sha384-B4morbeopVCSpzeC1c4nyV0d0cqvlSAfyXVfrPJa25im5p+yEN/YmhlgQP/OyMZD" crossorigin="anonymous">
</head>
<body>
    {% block content %}{% endblock content %}

    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>majestic | Landing, Ecommerce &amp; Business Templatee</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicons/favicon-16x16.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicons/favicon.ico' %}">
    <link rel="manifest" href="{% static 'assets/img/favicons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'assets/img/favicons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="{% static 'assets/css/theme.css' %}" rel="stylesheet" />

  </head>


  <body>

    <!-- ===============================================-->
    <!--    Main Content-->
    <!-- ===============================================-->
    <main class="main" id="top">
      {% include 'includes/navbar.html'  %}
      {% include 'includes/first_section.html' %}


      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/second_section.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->




      <!-- ============================================-->
      <!-- <section> begin ============================-->
     {% include 'includes/third_section.html' with products=products %}
      <!-- <section> close ============================-->
      <!-- ============================================-->




      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/section_four.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->


      {% include 'includes/section_five.html' %}


      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/collections.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->


     {% include 'includes/best_seller.html' %}


      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/outlet.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->




      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/explore.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->




      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/blog.html' %}
      
      <!-- <section> close ============================-->
      <!-- ============================================-->


      
        {% include 'includes/cta.html' %}

      <!-- ============================================-->
      <!-- <section> begin ============================-->
      {% include 'includes/footer.html' %}
      <!-- <section> close ============================-->
      <!-- ============================================-->


    </main>
    <!-- ===============================================-->
    <!--    End of Main Content-->
    <!-- ===============================================-->




    {% include 'includes/scripts.html' %}
  </body>

</html>

templates/includes/best_seller.html
<section>
    <div class="container">
      <div class="row h-100">
        <div class="col-lg-7 mx-auto text-center mb-6">
          <h5 class="fw-bold fs-3 fs-lg-5 lh-sm mb-3">Best Sellers</h5>
        </div>
        <div class="col-12">
          <div class="carousel slide" id="carouselBestSellers" data-bs-touch="false" data-bs-interval="false">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="10000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/handbag.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Marie Claire Handbag</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$399</span><span class="text-danger">$365</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/earrings.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Red Gem Earrings</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$489</span><span class="text-danger">$466</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/lathered-wristwatch.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Black Leathered Wristwatch</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$799</span><span class="text-danger">$745</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/tie.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Red-White Stripped Tie</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$299</span><span class="text-danger">$243</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="carousel-item" data-bs-interval="5000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/handbag.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Marie Claire Handbag</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$399</span><span class="text-danger">$365</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/earrings.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Red Gem Earrings</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$489</span><span class="text-danger">$466</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/lathered-wristwatch.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Black Leathered Wristwatch</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$799</span><span class="text-danger">$745</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/tie.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Red-White Stripped Tie</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$299</span><span class="text-danger">$243</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="carousel-item" data-bs-interval="3000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/handbag.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Marie Claire Handbag</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$399</span><span class="text-danger">$365</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/earrings.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Red Gem Earrings</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$489</span><span class="text-danger">$466</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/lathered-wristwatch.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Black Leathered Wristwatch</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$799</span><span class="text-danger">$745</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/tie.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Red-White Stripped Tie</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$299</span><span class="text-danger">$243</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="carousel-item">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/handbag.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Marie Claire Handbag</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$399</span><span class="text-danger">$365</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/earrings.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Red Gem Earrings</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$489</span><span class="text-danger">$466</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/lathered-wristwatch.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Black Leathered Wristwatch</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$799</span><span class="text-danger">$745</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                  <div class="col-md-3 mb-3 mb-md-0 h-100">
                    <div class="card card-span h-100 text-white"><img class="img-fluid h-100" src="assets/img/gallery/tie.png" alt="..." />
                      <div class="card-img-overlay ps-0"> </div>
                      <div class="card-body ps-0 bg-200">
                        <h5 class="fw-bold text-1000 text-truncate">Red-White Stripped Tie</h5>
                        <div class="fw-bold"><span class="text-600 me-2 text-decoration-line-through">$299</span><span class="text-danger">$243</span></div>
                      </div><a class="stretched-link" href="#"></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselBestSellers" data-bs-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="visually-hidden">Previous</span></button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselBestSellers" data-bs-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="visually-hidden">Next </span></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/includes/collections.html
{% load static %}
<section class="py-0" id="collection">

    <div class="container">
      <div class="row h-100 gx-2">
        <div class="col-md-6">
          <div class="card card-span h-100 text-white"><img class="card-img h-100" src="{% static 'assets/img/gallery/urban.png' %}" alt="..." />
            <div class="card-img-overlay bg-dark-gradient">
              <div class="p-5 p-md-2 p-xl-5">
                <h1 class="fs-md-4 fs-lg-7 text-light">Urban Stories </h1>
                <h5 class="fs-2 text-light">collection</h5>
              </div>
            </div><a class="stretched-link" href="#!"></a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card card-span h-100 text-white"><img class="card-img h-100" src="{% static 'assets/img/gallery/country.png' %}" alt="..." />
            <div class="card-img-overlay bg-dark-gradient">
              <div class="p-5 p-md-2 p-xl-5 d-flex flex-column flex-end-center align-items-baseline h-100">
                <h1 class="fs-md-4 fs-lg-7 text-light">Urban Stories </h1>
                <h5 class="fs-2 text-light">collection</h5>
              </div>
            </div><a class="stretched-link" href="#!"></a>
          </div>
        </div>
      </div>
    </div>
    <!-- end of .container-->

  </section>

templates/includes/cta.html
{% load static %}
<section class="py-11">
    <div class="bg-holder overlay overlay-0" style="background-image:url({% static 'assets/img/gallery/cta.png' %});background-position:center;background-size:cover;">
    </div>
    <!--/.bg-holder-->

    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="carousel slide carousel-fade" id="carouseCta" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="10000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-12">
                    <div class="text-light text-center py-2">
                      <h5 class="display-4 fw-normal text-400 fw-normal mb-4">visit our Outlets in</h5>
                      <h1 class="display-1 text-white fw-normal mb-8">London</h1><a class="btn btn-lg text-light fs-1" href="#!" role="button">See Addresses
                        <svg class="bi bi-arrow-right-short" xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                        </svg></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="carousel-item" data-bs-interval="5000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-12">
                    <div class="text-light text-center py-2">
                      <h5 class="display-4 fw-normal text-400 fw-normal mb-4">visit our Outlets in</h5>
                      <h1 class="display-1 text-white fw-normal mb-8">Bristol</h1><a class="btn btn-lg text-light fs-1" href="#!" role="button">See Addresses
                        <svg class="bi bi-arrow-right-short" xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                        </svg></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="carousel-item" data-bs-interval="3000">
                <div class="row h-100 align-items-center g-2">
                  <div class="col-12">
                    <div class="text-light text-center py-2">
                      <h5 class="display-4 fw-normal text-400 fw-normal mb-4">visit our Outlets in</h5>
                      <h1 class="display-1 text-white fw-normal mb-8">Birmingham</h1><a class="btn btn-lg text-light fs-1" href="#!" role="button">See Addresses
                        <svg class="bi bi-arrow-right-short" xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"> </path>
                        </svg></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <button class="carousel-control-prev" type="button" data-bs-target="#carouseCta" data-bs-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="visually-hidden">Previous</span></button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouseCta" data-bs-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="visually-hidden">Next </span></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

templates/products/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add Product{% endblock title %}
{% block content %}
<div style="margin: 1rem 4rem">
<form method="POST" action="{% url 'products:add_product' %}">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary btn-block" type="submit">Add Product</button>
</form>
</div>
{% endblock %}

templates/products/list.html
{% extends 'base.html' %}
{% block title %}Product List{% endblock title %}
{% block content %}
<a href="{% url 'products:add_product' %}">Add new product</a>
<ul class="list-group">
  {% for product in products %}
  <a href="{% url 'products:product_details' product.id %}">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      {{product.title}}
      <span class="badge bg-primary rounded-pill">{{product.price}}</span>
    </li>
  </a>
  {% endfor %}
  </ul>
{% endblock content %}